CREATE TABLE ORDER_FOLLOWUP (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    VR_NO VARCHAR2(50),
    ARRANGE_LOGISTIC VARCHAR2(10),
    QTY NUMBER,
    REMARKS VARCHAR2(1000),
    SALESPERSON VARCHAR2(100),
    CUSTOMER_NAME VARCHAR2(200),
    ITEM_NAME VARCHAR2(200),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
